Artist detail
bewizyu-formation/2019-D09-TiPunch-private-showcase-back pull request #7
Opened 2019-07-12 10:24 UTC by AlexandreRamade

2019-07-12 12:31 UTC, ingenieur-du-grenier approved these changes

2019-07-12 12:33 UTC, ingenieur-du-grenier reviewed
Travis est en echec sur la branche et la PR.

2019-07-12 12:33 UTC, ingenieur-du-grenier requested changes
Travis est en echec sur la branche et la PR

2019-07-12 13:58 UTC, bberthelemy commented on src/main/java/fr/formation/artistdetail/ArtistDetailService.java
> +    public void addNewArtistDetail(Artist artist, String photo, String longDescription, String site, int phoneNumber, List<String> departmentNames) {
En paramètres, tu pourrais passer directement ton objet dto pour éviter une liste importante de paramètres et gagner en simplification.
Si tu veux garder le coté "générique" alors la surcharge est une bonne solution, ça te permet d'avoir les 2, la généricité et la simplicité.

2019-07-12 13:58 UTC, bberthelemy commented on src/main/java/fr/formation/artistdetail/ArtistDetailRepository.java
> +    @Query("SELECT ad FROM ArtistDetail ad WHERE :department MEMBER OF ad.departments")
Penses a utiliser des constantes ou en tout cas faciliter la modification si besoin des éléments. Exemple, je change le nom de la table.

2019-07-12 13:58 UTC, bberthelemy commented on src/main/java/fr/formation/department/Department.java
> +    public String getName_uppercase() {
Essaie de garder une cohérence entre tes conventions de nomage. Soit du camelcase, soit du snakecase mais pas les deux ensemble. Ex : getName_uppercase -> soit get_name_uppercase soit -> getNameUppercase.

C'est la limite de la generation de code

2019-07-14 11:23 UTC, AlexandreRamade commented on src/main/java/fr/formation/department/Department.java
> +    public String getName_uppercase() {
J'ai fait le changement en gardant la norme camelcase.

2019-07-14 11:26 UTC, AlexandreRamade commented on src/main/java/fr/formation/artistdetail/ArtistDetailService.java
> +    public void addNewArtistDetail(Artist artist, String photo, String longDescription, String site, int phoneNumber, List<String> departmentNames) {
J'ai surchargé la méthode avec : addNewArtist(Artist artist, DetailArtistDTO detailArtistDto) {
C'est celle-ci que j'appelle maintenant depuis le Controler.

2019-07-15 07:32 UTC, merged